ifndef::snippets[]
:snippets: build/generated-snippets
endif::[]
= Rest Docs Structures API Document
:doctype: book
:toc: left
:sectnums:
:toclevels: 3
:source-highlighter: highlightjs
:operation-http-request-title: Example Request
:operation-request-fields-title: Request
:operation-http-response-title: Example Response
:operation-response-fields-title: Response

== 게시글 등록
operation::post-insert[snippets='http-request,request-fields,http-response']

== 게시글 목록
operation::board-list[snippets='http-request,http-response,response-body,response-fields']

== 나의 게시글 목록
operation::myBoard-list[snippets='http-request,http-response,response-body,response-fields']

== 게시글 상세보기
operation::post-detail[snippets='http-request,path-parameters,http-response,response-body,response-fields']

== 내 게시글 상세보기
operation::myPost-detail[snippets='http-request,path-parameters,http-response,response-body,response-fields']

== 게시글 수정
operation::post-update[snippets='http-request,path-parameters,http-response,response-body,response-fields']

== 게시글 삭제
operation::post-delete[snippets='http-request,path-parameters,http-response,response-body,response-fields']